name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install yarn
        run: npm i -g yarn

      - name: Installing Project Dependencies
        run: yarn

      - name: Generate static build
        run: yarn generate

      - name: Install SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Sync files to temporary location on Droplet
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ${{ github.workspace }}/dist/ \
          ikenna@144.126.202.220:/tmp/temp-deployment-dir/

      - name: Rsync files to protected directory with sudo on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ikenna@144.126.202.220 "echo ${{ secrets.DO_SUDO_PASSWORD }} | sudo -S rsync -avz --delete /tmp/temp-deployment-dir/ /var/www/zipkod.ng/"

      - name: Clean up temporary directory
        run: |
          ssh -o StrictHostKeyChecking=no ikenna@144.126.202.220 "rm -rf /tmp/temp-deployment-dir/"

      - name: Restart web server (optional)
        run: |
          ssh -o StrictHostKeyChecking=no ikenna@144.126.202.220 "sudo systemctl restart nginx"
