name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Installing Project Dependencies
        run: yarn

      - name: Generate static build
        run: yarn generate

      - name: Install SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Sync files to Droplet
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ${{ github.workspace }}/dist/ \
          ikenna@144.126.202.220:/home/ikenna/zipkod.ng

      - name: Restart web server (optional)
        run: |
          ssh -o StrictHostKeyChecking=no user@your-droplet-ip "sudo systemctl restart nginx"
